listen              1935;
max_connections     1000;
srs_log_tank        console;

# SRS HTTP API'si
http_api {
    enabled         on;
    listen          1985;
}

# Genel HTTP sunucusu
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    10;
        hls_window      60;
    }
}
